resource_id: "development:0"
# token gets used as the tenant ID when devtoken profile is activated in auth-service
auth_token: aaaaaa
tls:
  auth_service:
    url: http://localhost:8082
ambassador:
  address: localhost:6565
lumberjack:
  bind: localhost:5044
agents:
  dataPath: data-telemetry-envoy
