resource_id: "development:0"
tls:
  auth_service:
    url: http://localhost:8182
    token_provider: keystone_v2
ambassador:
  address: localhost:6565
lumberjack:
  bind: localhost:5044
agents:
  dataPath: data-telemetry-envoy
