version: '3.7'

services:
  authserv:
    image: ${IMG_PREFIX}salus-telemetry-auth-service
    ports:
      - 8082:8080
    networks:
      - infra
    env_file:
      - common.env
      - vault.env
    environment:
      # blank value enforces load from .env
      VAULT_APP_ROLE_ROLE_ID:
      # blank value enforces load from .env
      VAULT_APP_ROLE_SECRET_ID:
  resource-management:
    image: ${IMG_PREFIX}salus-telemetry-resource-management
    ports:
      - 8085:8080
    networks:
      - infra
    env_file:
      - common.env
      - jpa.env
      - kafka.env
  monitor-management:
    depends_on:
      - resource-management
    image: ${IMG_PREFIX}salus-telemetry-monitor-management
    ports:
      - 8089:8080
    networks:
      - infra
    env_file:
      - common.env
      - jpa.env
      - kafka.env
      - services.env
      - etcd.env
  agent-catalog-management:
    depends_on:
      - resource-management
    image: ${IMG_PREFIX}salus-telemetry-agent-catalog-management
    ports:
      - 8090:8080
    networks:
      - infra
    env_file:
      - common.env
      - jpa.env
      - kafka.env
      - services.env
  ambassador:
    depends_on:
      - resource-management
      - monitor-management
      - agent-catalog-management
    image: ${IMG_PREFIX}salus-telemetry-ambassador
    ports:
      - 6565:6565
      - 8081:8080
    networks:
      - infra
    env_file:
      - common.env
      - etcd.env
      - vault.env
      - kafka.env
      - services.env
    environment:
      # load from .env
      VAULT_APP_ROLE_ROLE_ID:
      # load from .env
      VAULT_APP_ROLE_SECRET_ID:
      AMBASSADOR_PUBLIC_ZONE_TENANTS: aaaaaa
      AMBASSADOR_EXTERNAL_NAME: localhost
      AMBASSADOR_VAULT_PKI_ROLE: telemetry-infra
  zone-watcher:
    image: ${IMG_PREFIX}salus-telemetry-zone-watcher
    ports:
      - 8084:8080
    networks:
      - infra
    env_file:
      - common.env
      - etcd.env
      - services.env
      - kafka.env
  presence-monitor:
    image: ${IMG_PREFIX}salus-telemetry-presence-monitor
    ports:
      - 8083:8080
    networks:
      - infra
    env_file:
      - common.env
      - etcd.env
      - kafka.env
      - services.env
  event-management:
    image: ${IMG_PREFIX}salus-event-engine-management
    ports:
      - 8087:8080
    networks:
      - infra
    env_file:
      - common.env
      - jpa.env
      - kapacitor.env
  event-ingest:
    image: ${IMG_PREFIX}salus-event-engine-ingest
    ports:
      - 8088:8080
    networks:
      - infra
    env_file:
      - common.env
      - kapacitor.env
      - kafka.env
  public-api:
    image: ${IMG_PREFIX}salus-telemetry-api-public
    ports:
      - 8080:8080
    networks:
      - infra
    env_file:
      - api.env
      - common.env
      - etcd.env
      - services.env
    environment:
      SPRING_PROFILES_ACTIVE: ${PUBLIC_API_PROFILES:-}
  admin-api:
    image: ${IMG_PREFIX}salus-telemetry-api-admin
    ports:
      - 8888:8080
    networks:
      - infra
    env_file:
      - api.env
      - common.env
      - etcd.env
    environment:
      SPRING_PROFILES_ACTIVE: ${ADMIN_API_PROFILES:-}

networks:
  infra:
    external: true
    name: telemetry-infra_default
