version: '3.2'

services:
  influxdb:
    image: influxdb:1.7.3
    ports:
      - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb
    environment:
      INFLUXDB_DB: salus

  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-6.7.2}
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana-config/datasources.yml:/etc/grafana/provisioning/datasources/main.yml:ro

volumes:
  influxdb:
  grafana:
